workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: 3.24.5
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create fresh android
        script: |
          flutter create --org com.blendjam --project-name blendjam --platforms android . --overwrite
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
