name: blendjam
description: BlendJam - Crossfade DJ mixer with auto 10s trim.
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: 0.9.40
  file_picker: 8.1.4
  audio_session: 0.1.21
  audiotags: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
