import 'dart:async';import 'dart:math' as m;import 'dart:typed_data';import 'package:audiotags/audiotags.dart';import 'package:file_picker/file_picker.dart';import 'package:flutter/material.dart';import 'package:just_audio/just_audio.dart';
void main()=>runApp(MaterialApp(theme:ThemeData.dark(),home:DJ()));class T{String p,n;T(this.p,this.n);}enum D{a,b}
class DJ extends StatefulWidget{const DJ({super.key});@override State<DJ>createState()=>S();}
class S extends State<DJ>{static const C=Color(0xFFCEBBFF);final a=AudioPlayer(),b=AudioPlayer();String?na,nb;Uint8List?aa,ab;D l=D.a;bool au=false,xf=false;double xv=0;List<T>q=[];int qi=0;Timer?tk;P(d)=>d==D.a?a:b;O(d)=>d==D.a?D.b:D.a;N(d)=>d==D.a?na:nb;A(d)=>d==D.a?aa:ab;SN(d,v){d==D.a?na=v:nb=v;}SA(d,v){d==D.a?aa=v:ab=v;}
@override void initState(){super.initState();a.playerStateStream.listen((s){if(s.processingState==ProcessingState.completed&&au&&!xf)_hn(D.a);});b.playerStateStream.listen((s){if(s.processingState==ProcessingState.completed&&au&&!xf)_hn(D.b);});tk=Timer.periodic(Duration(milliseconds:100),(_){_tick();});}
void _tick()async{if(!mounted||!au||xf)return;var pl=P(l);if(!pl.playing)return;var du=pl.duration;if(du==null)return;var rem=du.inMilliseconds-pl.position.inMilliseconds;var nd=O(l);if(rem<=15000&&rem>10000&&N(nd)==null)await _pr();if(rem<=10000&&N(nd)!=null&&!xf)await _fd(nd);}
@override void dispose(){tk?.cancel();a.dispose();b.dispose();super.dispose();}
void _force(D t){xf=false;l=t;xv=t==D.a?0:1;try{P(t).setVolume(1);P(O(t)).setVolume(0);}catch(_){}SN(O(t),null);SA(O(t),null);if(mounted)setState((){});}
void _hn(D d)async{if(!au||xf)return;var nd=O(d);if(N(nd)==null){var n=_nx();if(n!=null)await _ld(nd,n);}if(N(nd)!=null&&!P(nd).playing)await _fd(nd);}
T?_nx(){if(q.isEmpty)return null;var t=q[qi%q.length];qi=(qi+1)%q.length;return t;}
Future<Uint8List?>_ar(String p)async{try{var t=await AudioTags.read(p);if(t!=null&&t.pictures.isNotEmpty)return t.pictures.first.bytes;}catch(_){}return null;}
Future _ld(D d,T t,{bool lp=false})async{var pl=P(d);SN(d,t.n);SA(d,null);if(mounted)setState((){});try{await pl.stop();await pl.setFilePath(t.p);await pl.seek(Duration(milliseconds:200));await pl.setVolume(d==l?1:0);}catch(_){}if(lp){try{await pl.play();}catch(_){}}_ar(t.p).then((i){if(mounted){SA(d,i);setState((){});}});}
Future _pr()async{if(q.isEmpty||N(O(l))!=null||xf)return;var x=_nx();if(x==null)return;var nd=O(l);SN(nd,x.n);SA(nd,null);if(mounted)setState((){});try{await P(nd).stop();await P(nd).setFilePath(x.p);await P(nd).seek(Duration(milliseconds:200));await P(nd).setVolume(0);}catch(_){}_ar(x.p).then((i){if(mounted){SA(nd,i);setState((){});}});}
Future _au()async{if(q.isEmpty)return;if(N(l)==null){var f=_nx();if(f!=null){await _ld(l,f,lp:false);xv=l==D.a?0:1;await P(l).setVolume(1);try{await P(l).play();}catch(_){}}}else{try{await P(l).setVolume(1);await P(l).play();}catch(_){}}if(mounted)setState((){});}
Future _fd(D t)async{if(N(t)==null||xf)return;var s=l;var sp=P(s);var tp=P(t);if(!sp.playing&&tp.playing){l=t;xv=t==D.a?0:1;return;}xf=true;if(mounted)setState((){});try{await tp.setVolume(0);if(!tp.playing){try{await tp.seek(Duration(milliseconds:200));await tp.play();}catch(_){}}await Future.delayed(Duration(milliseconds:50));for(int i=0;i<=100;i++){var v=i/100.0;var av=m.cos(v*m.pi/2);var bv=m.sin(v*m.pi/2);if(s==D.a){xv=v;}else{xv=1-v;}try{await sp.setVolume(av);}catch(_){}try{await tp.setVolume(bv);}catch(_){}if(mounted)setState((){});if(i<100)await Future.delayed(Duration(milliseconds:100));}await sp.pause();await sp.setVolume(0);await tp.setVolume(1);SN(s,null);SA(s,null);l=t;xv=t==D.a?0:1;}catch(_){try{await tp.setVolume(1);}catch(_){}}finally{xf=false;if(mounted)setState((){});}}
Future _tg(D d)async{if(xf)return;var pl=P(d);if(pl.playing){await pl.pause();if(mounted)setState((){});return;}if(N(d)==null){var t=_nx();if(t!=null){await _ld(d,t,lp:true);l=d;xv=d==D.a?0:1;}}else if(d!=l){await _fd(d);}else{try{await pl.setVolume(1);await pl.play();}catch(_){}}if(mounted)setState((){});}
Future _pk(D d)async{var r=await FilePicker.platform.pickFiles(type:FileType.audio);if(r==null)return;var p=r.files.single.path;if(p!=null){if(P(l).playing&&d!=l){await _ld(d,T(p,r.files.single.name),lp:false);await P(d).setVolume(0);if(mounted)setState((){});}else{await _ld(d,T(p,r.files.single.name),lp:true);l=d;xv=d==D.a?0:1;}if(mounted)setState((){});}}
Future _aq()async{var r=await FilePicker.platform.pickFiles(type:FileType.audio,allowMultiple:true);if(r==null)return;setState(()=>q.addAll(r.files.where((f)=>f.path!=null).map((f)=>T(f.path!,f.name))));if(au)await _au();}
Future _sx(double v)async{xv=v;if(!xf){try{await a.setVolume(1-v);}catch(_){}try{await b.setVolume(v);}catch(_){}}if(mounted)setState((){});}
void _qp(){showModalBottomSheet(context:context,builder:(c){return SafeArea(child:Column(children:[ListTile(title:Text('QUEUE ${q.length}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(icon:Icon(Icons.add),onPressed:()async{await _aq();Navigator.pop(c);_qp();}),IconButton(icon:Icon(Icons.close),onPressed:()=>Navigator.pop(c))])),Expanded(child:ListView.builder(itemCount:q.length,itemBuilder:(x,i){var live=N(l)==q[i].n;return ListTile(dense:true,title:Text(q[i].n,overflow:TextOverflow.ellipsis,style:TextStyle(color:live?C:Colors.white)),onTap:()async{Navigator.pop(c);var d=O(l);if(P(l).playing){await _ld(d,q[i],lp:false);await P(d).setVolume(0);}else{await _ld(d,q[i],lp:true);l=d;xv=d==D.a?0:1;}});}))]));});}
Widget _dk(D d,bool up)=>Deck(deck:d,pl:P(d),name:N(d)??'No track',art:A(d),live:l==d,next:N(d)!=null&&l!=d,onPlay:()=>_tg(d),onPick:()=>_pk(d),onSeek:(s)async=>await P(d).seek(P(d).position+Duration(seconds:s)),lift:up);
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,title:Text('BlendJam'),actions
