import 'dart:async';import 'dart:math' as m;import 'dart:typed_data';import 'package:audiotags/audiotags.dart';import 'package:file_picker/file_picker.dart';import 'package:flutter/material.dart';import 'package:just_audio/just_audio.dart';
void main()=>runApp(MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(),home:DJ()));
class Q{String p,n;Q(this.p,this.n);}enum D{a,b}
class DJ extends StatefulWidget{const DJ({super.key});@override State<DJ> createState()=>_S();}
class _S extends State<DJ>{final a=AudioPlayer(),b=AudioPlayer();String? na,nb;Uint8List? aa,ab;double x=0;bool au=false,xg=false;D lv=D.a;List<Q> q=[];int qp=0;bool ar=false;
AudioPlayer P(D d)=>d==D.a?a:b;D O(D d)=>d==D.a?D.b:D.a;String? N(D d)=>d==D.a?na:nb;Uint8List? A(D d)=>d==D.a?aa:ab;
void SN(D d,String? v){d==D.a?na=v:nb=v;}void SA(D d,Uint8List? v){d==D.a?aa=v:ab=v;}
@override void initState(){super.initState();a.positionStream.listen((p)=>_ck(D.a,p));b.positionStream.listen((p)=>_ck(D.b,p));}
@override void dispose(){a.dispose();b.dispose();super.dispose();}
Q? _nl(){if(q.isEmpty) return null;var t=q[qp%q.length];qp=(qp+1)%q.length;return t;}
Future<Uint8List?> _art(String p) async{try{var t=await AudioTags.read(p);if(t!=null&&t.pictures.isNotEmpty) return t.pictures.first.bytes;}catch(_){}return null;}
Future<void> _ld(D d,Q t,{bool play=false}) async{SN(d,t.n);SA(d,null);setState((){});var pl=P(d);await pl.stop();await pl.setFilePath(t.p);await pl.seek(const Duration(milliseconds:200));_art(t.p).then((b){SA(d,b);if(mounted) setState((){});});await pl.setVolume(play?1:0);await pl.setSpeed(1);if(play){lv=d;x=d==D.a?0:1;await pl.play();}setState((){});}
Future<void> _as() async{if(q.isEmpty) return;if(N(lv)==null) await _ld(lv,_nl()!,play:true);if(N(O(lv))==null) await _ld(O(lv),_nl()!);}
void _ck(D d,Duration p){if(xg||ar) return;if(d!=lv) return;var du=P(d).duration;if(du==null||!P(d).playing) return;var r=du-p;if(au&&r.inSeconds==15){var f=O(lv);if(N(f)==null) _ld(f,_nl()!);}if(r.inSeconds<=10&&r.inSeconds>=9){if(N(D.a)!=null&&N(D.b)!=null){ar=true;_fade();}}}
void _fade(){if(xg) return;var s=lv,t=O(s);if(N(t)==null){ar=false;return;}xg=true;var sp=P(s),tp=P(t);tp.setVolume(0);tp.setSpeed(1);tp.play();int k=0;Timer.periodic(const Duration(milliseconds:100),(tm) async{k++;double v=k/50;if(v>1) v=1;x=s==D.a?v:1-v;sp.setVolume(1-x);tp.setVolume(x);setState((){});if(k>=50){tm.cancel();x=s==D.a?1:0;sp.setVolume(0);tp.setVolume(1);await sp.stop();SN(s,null);SA(s,null);lv=t;xg=false;ar=false;setState((){});if(au&&N(O(lv))==null&&q.isNotEmpty) _ld(O(lv),_nl()!);}});}
Future<void> _pk(bool isA) async{var r=await FilePicker.platform.pickFiles(type:FileType.audio);if(r==null) return;var tg=P(lv).playing?O(lv):(isA?D.a:D.b);await _ld(tg,Q(r.files.single.path!,r.files.single.name));}
Future<void> _aq() async{var r=await FilePicker.platform.pickFiles(type:FileType.audio,allowMultiple:true);if(r==null) return;setState(()=>q.addAll(r.files.where((f)=>f.path!=null).map((f)=>Q(f.path!,f.name))));}
Future<void> _nx(D d) async{if(q.isEmpty) return;await _ld(d,_nl()!);}
Future<void> _pv(D d) async{if(q.isEmpty) return;qp=(qp-2+q.length)%q.length;var t=q[qp%q.length];qp=(qp+1)%q.length;await _ld(d,t);}
Widget _disc(bool isA){var d=isA?D.a:D.b;var pl=P(d);return _V(d:d,pl:pl,na:N(d)??'No track selected',ar:A(d),live:lv==d,nxt:O(lv)==d&&N(d)!=null,onPk:()=>_pk(isA),onPP:()async{if(pl.playing){await pl.pause();}else{if(N(d)==null&&q.isNotEmpty){await _ld(d,_nl()!,play:true);}else{lv=d;x=d==D.a?0:1;pl.setVolume(1);await pl.setSpeed(1);P(O(d)).setVolume(0);await pl.play();}setState((){});}},onNext:()=>_nx(d),onPrev:()=>_pv(d),onF:(int s) async{var p=pl.position+Duration(seconds:s);if(p<Duration.zero) p=Duration.zero;await pl.seek(p);});}
@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('BlendJam',style:TextStyle(fontWeight:FontWeight.bold)),actions:[const Text('AUTO',style:TextStyle(fontSize:12,fontWeight:FontWeight.bold)),Switch(value:au,activeColor:const Color(0xFFCEBBFF),onChanged:(v)async{setState(()=>au=v);if(v) await _as();}),const SizedBox(width:10)]),body:ListView(padding:const EdgeInsets.all(14),children:[_disc(true),Padding(padding:const EdgeInsets.symmetric(horizontal:10,vertical:2),child:Row(children:[const Text('A',style:TextStyle(fontSize:12,fontWeight:FontWeight.bold)),Expanded(child:Slider(value:x,min:0,max:1,activeColor:const Color(0xFFCEBBFF),onChanged:(v){if(xg) return;x=v;a.setVolume(1-v);b.setVolume(v);if(v>=0.5&&N(D.b)!=null) lv=D.b;if(v<0.5&&N(D.a)!=null) lv=D.a;setState((){});})),const Text('B',style:TextStyle(fontSize:12,fontWeight:FontWeight.bold))])),Center(child:Text(xg?'MIXING ${(x*100).toInt()}%':'',style:const TextStyle(fontSize:11,color:Color(0xFFCEBBFF),fontWeight:FontWeight.bold))),_disc(false),const SizedBox(height:14),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('QUEUE ${q.length} (loops)',style:const TextStyle(fontSize:14,fontWeight:FontWeight.bold)),IconButton(iconSize:28,icon:const Icon(Icons.add_circle),onPressed:_aq)]),...q.map((e)=>ListTile(dense:true,title:Text(e.n,style:const TextStyle(fontSize:13),maxLines:1,overflow:TextOverflow.ellipsis),onTap:()async{var tg=P(lv).playing?O(lv):(N(lv)==null?lv:O(lv));await _ld(tg,e);}))]));}}

class _V extends StatefulWidget{final D d;final AudioPlayer pl;final String na;final Uint8List? ar;final bool live,nxt;final VoidCallback onPk,onPP,onPrev,onNext;final Function(int) onF;const _V({required this.d,required this.pl,required this.na,required this.ar,required this.live,required this.nxt,required this.onPk,required this.onPP,required this.onPrev,required this.onNext,required this.onF});@override State<_V> createState()=>_VS();}
class _VS extends State<_V> with TickerProviderStateMixin{late AnimationController r,w;bool scr=false;
@override void initState(){super.initState();r=AnimationController(vsync:this,duration:const Duration(seconds:3));w=AnimationController(vsync:this,duration:const Duration(milliseconds:500))..repeat();widget.pl.playerStateStream.listen((s){if(!scr){if(s.playing) r.repeat();else r.stop();}});}
@override void dispose(){r.dispose();w.dispose();super.dispose();}
@override Widget build(BuildContext c){return Column(children:[Text('DECK ${widget.d==D.a?'A':'B'} ${widget.live?'(LIVE)':widget.nxt?'(NEXT)':''}',style:TextStyle(fontSize:14,fontWeight:FontWeight.bold,color:widget.live?const Color(0xFFCEBBFF):Colors.white70)),const SizedBox(height:8),
GestureDetector(
onPanStart:(_) async{scr=true;r.stop();await widget.pl.setSpeed(0);},
onPanUpdate:(d) async{var dx=d.delta.dx;if(dx.abs()<0.5) return;r.value=(r.value+dx*0.02)%1;var np=widget.pl.position+Duration(milliseconds:(dx*350).toInt());if(np<Duration.zero) np=Duration.zero;var du=widget.pl.duration;if(du!=null&&np>du) np=du-Duration(milliseconds:100);await widget.pl.seek(np);var sp=(dx*0.8).clamp(-4.0,4.0);await widget.pl.setSpeed(sp.abs()<0.2?0:sp);},
onPanEnd:(_) async{scr=false;await widget.pl.setSpeed(1);if(widget.pl.playing) r.repeat();},
child:SizedBox(width:220,height:220,child:Stack(alignment:Alignment.center,children:[AnimatedBuilder(animation:w,builder:(c,_){return CustomPaint(size:const Size(220,220),painter:_WP(anim:w.value,live:widget.live,play:widget.pl.playing));}),RotationTransition(turns:r,child:Container(width:190,height:190,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:widget.live?const Color(0xFFCEBBFF):Colors.white24,width:3),boxShadow:[BoxShadow(color:Colors.black.withOpacity(0.7),blurRadius:12)]),child:ClipOval(child:Stack(fit:StackFit.expand,children:[widget.ar!=null?Image.memory(widget.ar!,fit:BoxFit.cover):Container(color:const Color(0xFF2A2A2A),child:const Icon(Icons.album,size:90,color:Colors.white24)),Container(decoration:BoxDecoration(gradient:RadialGradient(colors:[Colors.black.withOpacity(0.1),Colors.black.withOpacity(0.6)]))),Center(child:Container(width:64,height:64,decoration:BoxDecoration(shape:BoxShape.circle,color:const Color(0xFFCEBBFF),border:Border.all(color:Colors.black,width:2)),child:IconButton(iconSize:32,icon:StreamBuilder<PlayerState>(stream:widget.pl.playerStateStream,builder:(c,s)=>Icon(s.data?.playing==true?Icons.pause:Icons.play_arrow,color:Colors.black,size:32)),onPressed:widget.onPP)))]))))]))),
const SizedBox(height:8),
SizedBox(width:230,child:Text(widget.na,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w600,color:Colors.white),maxLines:1,overflow:TextOverflow.ellipsis,textAlign:TextAlign.center)),
StreamBuilder<Duration>(stream:widget.pl.positionStream,builder:(c,s){var p=s.data??Duration.zero;var du=widget.pl.duration??const Duration(seconds:1);var pr=du.inMilliseconds>0?p.inMilliseconds/du.inMilliseconds:0.0;String f(Duration d)=>'${d.inMinutes.remainder(60).toString().padLeft(2,'0')}:${(d.inSeconds.remainder(60)).toString().padLeft(2,'0')}';return Column(children:[SizedBox(width:240,child:SliderTheme(data:SliderThemeData(thumbShape:const RoundSliderThumbShape(enabledThumbRadius:8),trackHeight:4),child:Slider(value:pr.clamp(0.0,1.0),min:0,max:1,activeColor:widget.live?const Color(0xFFCEBBFF):Colors.white54,onChanged:(v) async{var np=Duration(milliseconds:(v*du.inMilliseconds).toInt());await widget.pl.seek(np);},onChangeStart:(_){scr=true;},onChangeEnd:(_){scr=false;}))),Text('${f(p)} / ${f(du)}',style:const TextStyle(fontSize:11,color:Colors.white38)),
Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(iconSize:24,icon:const Icon(Icons.skip_previous),onPressed:widget.onPrev,tooltip:'Prev Track'),IconButton(iconSize:22,icon:const Icon(Icons.replay_10),onPressed:()=>widget.onF(-10),tooltip:'-10s'),IconButton(iconSize:30,icon:const Icon(Icons.folder_open),onPressed:widget.onPk),IconButton(iconSize:22,icon:const Icon(Icons.forward_10),onPressed:()=>widget.onF(10),tooltip:'+10s'),IconButton(iconSize:24,icon:const Icon(Icons.skip_next),onPressed:widget.onNext,tooltip:'Next Track')]),
const Text('drag disc=scratch | slider=seek | skip=prev/next track',style:TextStyle(fontSize:7,color:Colors.white24))]);})]);}}
class _WP extends CustomPainter{final double anim;final bool live,play;_WP({required this.anim,required this.live,required this.play});@override void paint(Canvas c,Size s){var o=Offset(s.width/2,s.height/2);var b=102.0;var p=Paint()..style=PaintingStyle.stroke..strokeWidth=1.6..color=live?const Color(0xFFCEBBFF).withOpacity(0.9):Colors.white24.withOpacity(0.3);var pa=Path();for(int i=0;i<=120;i++){var a=(i/120)*2*m.pi;double am=play?6*m.sin(i*0.7+anim*8):1.5*m.sin(i*0.4);var r=b+am;var x=o.dx+r*m.cos(a);var y=o.dy+r*m.sin(a);if(i==0) pa.moveTo(x,y);else pa.lineTo(x,y);}pa.close();c.drawPath(pa,p);}@override bool shouldRepaint(covariant _WP old)=>old.anim!=anim;}
