name: Build APK

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flutter project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      - name: Check Flutter installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Generate Android project
        run: |
          flutter create \
            --platforms=android \
            --project-name blendjam \
            .

      - name: Set Android compile SDK
        run: |
          sed -i \
            's/compileSdk = flutter.compileSdkVersion/compileSdk = 35/' \
            android/app/build.gradle

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Generate app icon
        run: |
          dart run flutter_launcher_icons

      - name: Build APK
        run: |
          flutter build apk \
            --release \
            --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: blendjam-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
